version: '3'
services:
  project_node:
    build: node
    container_name: project_node
    restart: always
    volumes:
      - ../:/usr/src/app
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/app
    command: npm run start:watch
    ports:
      - 3000:3000
    networks:
      - project-network
  project_mysql:
    image: mysql:5.7
    container_name: project_mysql
    restart: always
    # expose:
    #   - 3306
    environment:
      - MYSQL_DATABASE=skillific
      - MYSQL_ROOT_PASSWORD=abc@123
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    ports:
      - 3307:3306
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
    networks:
      - project-network
networks:
  project-network:
    driver: bridge
